### ISSUE TITLE
Proposal: List functions without any form of authentication

### ISSUE THREAD

**Issue by MineMS49** [openfaas/faas-provider#13]
Create a new endpoint, like `/functions`, with only the functions' names in a JSON format which can be called from an upper API in order to display them.

The JSON could be like this :
``` javascript
[
    {
        "name": "<function_name_1>",
        "labels": {
            "function": "true"
        }
    },
    {
        "name": "<function_name_2>",
        "labels": {
            "function": "true"
        }
    },
    {
        "name": "<function_name_3>",
        "labels": {
            "function": "true"
        }
    },
    {
        "name": "<function_name_...>",
        "labels": {
            "function": "true"
        }
    },
    {
        "name": "<function_name_n>",
        "labels": {
            "function": "true"
        }
    }
]
```
Note : This JSON is already used for the endpoint `/system/functions` with only `"name"` and `"function"` in `"labels"` keys

This will avoid any call to `/system/functions` and/or passing credential in a function or environment variables.
A feature of this endpoint can be to be allowed or not in a parameter when installing OpenFaas

**Comment by ivanayov** [comment]
Derek add label: proposal

**Comment by ivanayov** [comment]
Hi @MineMS49 ,

What is your use-case and the motivation for this?
How the available `/system/functions` endpoint does not work in that case?

I suppose you need the functions list without authentication. Can you give us more details?

Thanks,
Ivana

**Comment by MineMS49** [comment]
Thank you for the reply @ivanayov,

The use case is pretty simple:

```
A user call a function
A filtering function receives parameters and permission for this user
Before sending the request, it checks if the function exists
It sends the request
It pulls back to the user the result
```

Here, as `/system/functions` can be accessed only with authentication there is no other way to check if the function called exists.
It annoys me to enter credentials in the filter function that's why I'm looking for an endpoint that has the list of all functions without authentication.

Of course, getting the functions list from `/system/functions` is possible and there's no problem about that. The point is, between the interface and the service, there are external access that can listen and read packets passing by.

**Comment by ivanayov** [comment]
Let's get some feedback on your proposal from the community.
I think it can be a security leak to give access to function names in production.

But meanwhile you can solve your problem by checking if the function url exists. Would that work for you?

**Comment by MineMS49** [comment]
Ok, I understand more of the problem that can lead to a security leak. I thought about it and I suggest with a slightly different proposal :
→ Add a new user to OpenFaas which has access in read only to a new endpoint. This means there's no more issues with the admin credential and also, as it still needs an authentication, no information will be exposed.

From my point of view it's a feature that can be added, but not enabled by default to prevent any bad use.

I made a visual explanation of the current situation and the proposal I'm talking about.

![faas-provider](https://user-images.githubusercontent.com/43464448/50077954-09cc4a80-01e6-11e9-8eaf-46c904407916.png)

**Comment by ivanayov** [comment]
Derek set title: Add non-admin user with read-only permissions

**Comment by ivanayov** [comment]
Derek add label: proposal

**Comment by ivanayov** [comment]
Thanks for your proposal @MineMS49

**Comment by ivanayov** [comment]
Meanwhile, did the URL check help you?

**Comment by alexellis** [comment]
I'm still trying to understand the use-case and I'm not quite getting to that yet. This proposal is starting to look really complicated.

What is the trouble/issue as you are experiencing it now? Perhaps there is more than one way to resolve the issue for you other than the solution being proposed. I do find it helps to dig deeper into the issue rather than starting with a solution.

I'm hearing that you want to list functions without any security protecting that endpoint/method?

Alex

**Comment by alexellis** [comment]
@MineMS49 I am going to close this issue, but feel free to comment and revisit if needed.
