### ISSUE TITLE
Re-vendor into all "official" providers

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-provider#17]
The "health" handler was renamed from "Health" to "HealthHandler" which is a breaking change and requires an upgrade to all providers:

- faas-swarm
- faas-netes
- openfaas-operator

Task:

* Checkout each provider
* Vendor https://github.com/openfaas/faas-provider/releases/tag/0.9.0 with `dep ensure` or an edit to `Gopkg.toml`
* Update the main or app or server.go to do the rename
* Build / make / test with Docker & `go build`
* Raise PR
* 👍

**Comment by martindekov** [comment]
Derek assign: me

**Comment by ewilde** [comment]
@martindekov didn’t see the issue I’ve don swarm https://github.com/openfaas/faas-swarm/pull/49

**Comment by martindekov** [comment]
Thanks @ewilde repo— 😀

**Comment by martindekov** [comment]
Derek reopen
