### ISSUE TITLE
Proxy status code is always 200 OK 

### ISSUE THREAD

**Issue by ewilde** [openfaas/faas-provider#18]
https://github.com/openfaas/faas-provider/blob/6a76a052deb12fd94b373c082963d8a8ad44d4d1/proxy/proxy.go#L135-L152

Apologies if this was the intention! Just want to understand why we don't proxy the status code back on the response to the client. I got tripped up up debugging an issue where the upstream provider was returning `404`, but downstream the response to the client was `200`

https://github.com/openfaas/faas-provider/blob/6a76a052deb12fd94b373c082963d8a8ad44d4d1/proxy/proxy.go#L151

**Comment by alexellis** [comment]
One for @lucasroesler perhaps?

I would expect this to return the upstream status code. The code path is not enabled on swarm or Kubernetes by default.

**Comment by LucasRoesler** [comment]
Derek unassign: me

**Comment by LucasRoesler** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Thanks for picking this up
