### ISSUE TITLE
Add namespace support for logs

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-provider#30]
The logs request/response should include support for specifying the namespace to support 

https://github.com/openfaas/faas-netes/issues/511

This value can optionally be ignored depending on the provider implementation.

**Comment by alexellis** [comment]
@LucasRoesler is this complete now or still pending?

**Comment by LucasRoesler** [comment]
Still pending

**Comment by LucasRoesler** [comment]
@alexellis it should be resolved by the attached PR
