### ISSUE TITLE
Add namespace support to the proxy package

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-provider#31]
The proxy package needs to clearly support selecting functions by namespace in order to support 

https://github.com/openfaas/faas-netes/issues/511

**Comment by alexellis** [comment]
@LucasRoesler is this complete now or still pending for the proxy?

**Comment by LucasRoesler** [comment]
still pending, i think

**Comment by LucasRoesler** [comment]
@alexellis i am not sure a change is actually needed? I think this was opened originally to make sure we didn't forget.  But the implementation in faas-netes kind of shows that the current interface seems to be flexible enough. We can probably close it unless you think there is a specific feature that we haven't been able to implement in faas-netes yet because of the proxy implementation

**Comment by alexellis** [comment]
Sounds good to me. Thank you for the detailed reply.
