### ISSUE TITLE
InfoRequest should be named InfoResponse

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-provider#38]
This struct https://github.com/openfaas/faas-provider/blame/master/types/requests.go#L12

Is actually used as a response, so it should be called `InfoResponse`.  See https://github.com/openfaas/faas-swarm/blob/ecf4229ce7dea59ccf8bbf3f96e6f11a669ffe60/handlers/info.go#L18-L43 and https://github.com/openfaas/faas-netes/blob/85492c470c36065f8dc2bba59b5a212d7779a2e9/handlers/info.go#L21-L46

The current name can be confusing when implementing a new provider.

Also, it seems like we could probably completely standardize the the `InfoHandler` by passing the provider version info, name, and identifier to https://github.com/openfaas/faas-provider/blob/d6579bdcf7c85f4d01f398d65ea0cab37e9633d0/serve.go#L32 via the FaasConfig object

**Comment by alexellis** [comment]
Please fix the naming 👍 I'll cut a new release for you after that.

**Comment by LucasRoesler** [comment]
Do you want me to keep it backwards compatible, leaving the old name for now, or just create a breaking change?
