### ISSUE TITLE
[Question] Should we remove the Dockerfile

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-provider#40]
I was about to open a PR for the Go modules migration when I realized that this Dockerfile may need to be updated https://github.com/openfaas/faas-provider/blob/master/Dockerfile

But then I realized I wasn't sure what it was for. It is not referenced in the CI flow or the Readme.  It looks like it was an early demo prototype for how the `faas-provider` works. The Readme now references the concrete implementation in faas-netes, perhaps we can remove this Dockerfile?

**Comment by alexellis** [comment]
I added this and was using it as a sample to show how to build a simple provider. I don't mind if you would like to delete it.
