### ISSUE TITLE
Issue with link to server.go in README.md

### ISSUE THREAD

**Issue by mkimberley** [openfaas/faas-provider#42]
The read me provides a link to "server.go" describing the process for using the faas-provider package, but the link is broken:

on line 23: For an example see the [server.go](https://github.com/openfaas/faas-netes/blob/master/server.go) file in the [faas-netes](https://github.com/openfaas/faas-netes) Kubernetes backend.

**Comment by alexellis** [comment]
I think it might be main.go now? Feel free to send a PR to fix. Don't use the GitHub UI unless you add the sign off message manually. 

git commit -s should do it

**Comment by mkimberley** [comment]
Resolved with commit f665901
