### ISSUE TITLE
Copy remaining request structs from the gateway

### ISSUE THREAD

**Issue by LucasRoesler** [openfaas/faas-provider#44]
While working on the certifier, I wanted to update the vendored code and I realized that many of the request structs had moved to the provider (see #22) but `AsyncReport` and `DeleteFunctionRequest` are both still in the gateway.

At the minimum it seems like we should move the delete request.  the `AsyncReport` seems like a response type, not a request type, but it probably make sense to move it too.

**Comment by alexellis** [comment]
The async report isn't about the provider, but the gateway. The delete function request is part of the provider though, so could move.

**Comment by LucasRoesler** [comment]
Perhaps there should be an `async-provider` 😆

**Comment by alexellis** [comment]
@LucasRoesler I was looking at faasd and we still reference openfaas/faas just to be able to add "DeleteFunctionRequest" - do you want to move it over to this project so we can try to remove that remaining reference?

**Comment by LucasRoesler** [comment]
Sure, will do
