### ISSUE TITLE
Fix 0.12.1 tag

### ISSUE THREAD

**Issue by wilsonianb** [openfaas/faas-provider#46]
Version 0.12.1 was tagged as `012.1`.

Tools like [`dep`](https://github.com/golang/dep) are currently pulling it in as version 12.1.0, making it the latest release.

**Comment by alexellis** [comment]
The tag to be used is: https://github.com/openfaas/faas-provider/releases/tag/v0.15.1

I don't think you can remove tags from git history? Any suggestions?
