### ISSUE TITLE
Add route - /system/id

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-provider#5]
The `/system/id` endpoint should reveal the provider name.

This will be called by the OpenFaaS gateway for external providers so we can for instance hide the "networking" field or show which orchestrator is being used.

https://github.com/openfaas/faas-provider/blob/master/serve.go#L24

**Comment by BurtonR** [comment]
I'll work on this. Hope to have it done this weekend

**Comment by alexellis** [comment]
Please propose a JSON body for the format and ping Stefan for his feedback.

**Comment by alexellis** [comment]
@BurtonR we need to establish a format here. Pinging @stefanprodan 

```json
{
  "provider": "faas-netes",
  "version": {
    "sha": "xyz",
    "release": "0.2.2"
  },
  "orchestration": "kubernetes"
}
```

**Comment by stefanprodan** [comment]
The JSON body looks good 👍

**Comment by BurtonR** [comment]
To be clear, this is just to define the format and add a `struct` that the underlying provider would need to implement, correct?

The value in `"orchestration"` could be `"swarm"`, `"ecs"`, `"rancher"` etc?

**Comment by alexellis** [comment]
Yes add a struct for it

**Comment by stefanprodan** [comment]
An implementation example can be found at: https://github.com/openfaas-incubator/faas-o6s/pull/8/commits/97963d4bde303bde9b553c79c1abd5d088af5ff4
