### ISSUE TITLE
More specific error response for timeout

### ISSUE THREAD

**Issue by francisdb** [openfaas/faas-provider#61]
`faas-netes` log

> 2022/01/14 10:07:51 error with proxy request to: http://10.32.130.24:8080, Post \"http://10.32.130.24:8080\": context canceled

`gateway` logs

> 2022/01/14 10:07:51  Forwarded [POST] to /function/fn-2100e53c784e4a88a864449e78ba50b462703696.openfaas-fn-6ccc8843-d78d-49e8-84c4-3734a4af9929 - [500] - 120.004119s seconds

On our side we get a `500` containing "Can't reach service"
We have in the past also seen 502's without body for timeouts from https://github.com/openfaas/faas/blob/52d0165c3f22b5d1c269dd6e43e6e6bda6559936/gateway/handlers/forwarding_proxy.go#L132

Towards our users we would like to report this as a timeout, a few questions pop up:

* How do we know a response comes from the openfaas middleware vs the actual function? Maybe some specific headers can be set for all responses from openfaas proxies?
* How do we reconstruct this is a timeout from the generic "Can't reach service"? A standardized error response format would be welcome.
* Any reason why there is no standard log format in use on openfaas components where log level, namespace, deployment and other info can be filtered on?

Reported here as this repo came up searching for the error messages

**Comment by alexellis** [comment]
Hi @francisdb we've started adding an X-OpenFaaS-Internal header, this may be of some use if you're still working on this problem a year later.
